### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by AlessandroZoia-dev** [kolesman/SEC#20]
Hi, I have the following error:
/_caffe.so: undefined symbol: _ZN5caffe3NetIfE21CopyTrainedLayersFromERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
terminate called after throwing an instance of 'boost::python::error_already_set'
*** Aborted at 1636388098 (unix time) try "date -d @1636388098" if you are using GNU date ***
PC: @     0x7fb7edd7afb7 gsignal
*** SIGABRT (@0x3eb0000165a) received by PID 5722 (TID 0x7fb7f0105200) from PID 5722; stack trace: ***
    @     0x7fb7edd7b040 (unknown)
    @     0x7fb7edd7afb7 gsignal
    @     0x7fb7edd7c921 abort
    @     0x7fb7ee3d1957 (unknown)
    @     0x7fb7ee3d7ae6 (unknown)
    @     0x7fb7ee3d7b21 std::terminate()
    @     0x7fb7ee3d7da9 __cxa_rethrow
    @     0x7fb7ef523aef caffe::GetPythonLayer<>()
    @     0x7fb7ef643300 caffe::Net<>::Init()
    @     0x7fb7ef645e4e caffe::Net<>::Net()
    @     0x7fb7ef650836 caffe::Solver<>::InitTrainNet()
    @     0x7fb7ef650e14 caffe::Solver<>::Init()
    @     0x7fb7ef6510ff caffe::Solver<>::Solver()
    @     0x7fb7ef66e831 caffe::Creator_SGDSolver<>()
    @     0x55cb7c8cdf70 train()
    @     0x55cb7c8ca37b main
    @     0x7fb7edd5dbf7 __libc_start_main
    @     0x55cb7c8cad6a _start

but caffe is correctly installed with WITH_PYTHON_LAYER := 1.  I compiled using the commands:

make all -j6       # 6 represents number of CPU Cores
make pycaffe -j6   # 6 represents number of CPU Cores

Can you help me? Thanks

**Comment by AlessandroZoia-dev** [comment]
Solved this problem, I had another caffe installation ....
Now the training starts but I have the following problem:

Traceback (most recent call last):
  File "/home/alessandro/SEC/sec-evn2/local/lib/python2.7/site-packages/pylayers/pylayers.py", line 71, in forward
    self.result[i] = CRF(im[i], unary[i], scale_factor=12.0)
  File "/home/alessandro/SEC/sec-evn2/local/lib/python2.7/site-packages/krahenbuhl2013/CRF.py", line 19, in CRF
    assert(image.shape[:2] == unary.shape[:2])

Can you help me? Thanks
