### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by munirfarzeen** [kolesman/SEC#5]
hi,
im trying to train the network. im getting the following error. any idea how to fix it?

Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "/home/mlv/object/SEC/pylayers/pylayers/__init__.py", line 1, in <module>
    from .pylayers import *
  File "/home/mlv/object/SEC/pylayers/pylayers/pylayers.py", line 11, in <module>
    from krahenbuhl2013 import CRF
  File "/home/mlv/object/SEC/CRF/krahenbuhl2013/__init__.py", line 1, in <module>
    from .CRF import *
  File "/home/mlv/object/SEC/CRF/krahenbuhl2013/CRF.py", line 1, in <module>
    from krahenbuhl2013.wrapper import DenseCRF
ImportError: No module named wrapper

**Comment by Irtza** [comment]
@likui01 From project directory you should `pip install CRF/` to build the wrapper

**Comment by XYZsake** [comment]
Hello, I have the same problem, and it doesn't work after `pip install CRF/`. Could you tell me how you solve this problem? Thank you.

**Comment by sreesindhu-sabbineni** [comment]
I have the same issue. Even after `pip install CRF/`. Can you tell me how to solve this problem?
